export PATH="$HOME/.local/bin:$PATH"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

export EDITOR=nano
export VISUAL=nano

alias ls='ls --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias ..='cd ..'
alias ...='cd ../..'
alias theme='bash ~/.termux-theme/apply.sh'
alias themes='ls ~/.termux-theme/themes'
alias banner='bash ~/.termux-theme/banner.sh'

clear
bash ~/.termux-theme/banner.sh show
echo ""
echo "  date    : $(date '+%A, %d %B %Y')"
echo "  time    : $(date '+%H:%M:%S')"
echo "  storage : $(df -h /data | awk 'NR==2 {print $3 " / " $2 " (" $5 " used)"}')"
echo ""
