use-black-ui = false
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]
terminal-margin-horizontal = 4
terminal-margin-vertical = 4
bell-character = ignore
